version: '3.8'

services:
  jobmanager:
    image: flink:scala_2.11-java8
    ports:
      - "8081:8081"
      - "6123:6123"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    entrypoint: 
      - sh 
      - -c  
      - |
        sed -i 's/start-foreground/start/g' /docker-entrypoint.sh
        /docker-entrypoint.sh jobmanager
        sleep 10 && tail -f -n +0 /opt/flink/log/*

  taskmanager:
    image: flink:scala_2.11-java8
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    depends_on:
      - jobmanager
    scale: 2
    entrypoint: 
      - sh 
      - -c  
      - |
        sed -i 's/start-foreground/start/g' /docker-entrypoint.sh
        /docker-entrypoint.sh taskmanager
        sleep 10 && tail -f -n +0 /opt/flink/log/*
